FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest

WORKDIR /app

COPY . ./

RUN install_packages apt-utils wget

# Next line will be the CMD when using local mode
# dev-cmd-live=balena-idle

# Next line will be the CMD in "production" (not in local mode)
CMD [ "/bin/bash", "/app/start.sh"]